### ISSUE TITLE
[Feat] 서버 통신 마무리 하기

### ISSUE THREAD

**Issue by HELLOHIDI** [sopkathon-32nd-10/IgoBossiOS#46]
## 🛠 Issue
- 서버 통신 마무리 하기

## 📋 To-do
- [ ] 메인 서버 데이터 붙이기
- [ ] 임금 계산 서버 붙이기
- [ ] 체크리스트 서버 문제 해결하기
